# wordpress-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-app-config
  namespace: wordpress-application
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_USER: wordpress_usr
  WORDPRESS_DB_PASSWORD: wordpress
  WORDPRESS_DB_NAME: wordpress_db
